# sudo ln -s $(pwd)/etc/nginx/nginx.logrotate.conf /etc/logrotate.d/nginx.logrotate.conf

/home/*/log/*.log {
  daily
  #dateext
  #dateformat -%Y-%m-%d
  missingok
  rotate 12
  
  postrotate
    [ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`
    invoke-rc.d nginx rotate >/dev/null 2>&1
  endscript
	
}
